In [67]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [68]:
titanic_data = pd.read_csv("titanic.csv")
titanic_data.head()
# My first intuition is, Ticket number, and their name is irrelevant in this model
# Name, PassengerId should be excluded
# the label is Survived

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [69]:
# making the dataset ready
X = titanic_data.drop(columns=["PassengerId", "Name", "Ticket", "Survived", "Cabin"])
y = titanic_data["Survived"]

encoder = LabelEncoder()
X["Sex"] = encoder.fit_transform(X["Sex"])

X = pd.get_dummies(X, columns=['Embarked'], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
# Scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

imputer = SimpleImputer(strategy="mean")  # or "median", "most_frequent"
X_train_scaled = imputer.fit_transform(X_train_scaled)

In [ ]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)